---
title: "Exportación de los polígonos"
date: 24 11 2022
date-format: long
fig-cap-location: top
execute: 
    warning: false
    message: false
---

## Exportación

En la última reunión se acordó con el prof. Pedro Achancaray que las observaciones se exportarían en 11 bases de datos correspondientes a cada mes en cuestión (desde enero hasta noviembre) de manera que cada base acumulará los meses precedentes.

```{r}
#| output: false
#| label: setup

pacman::p_load(raster, stars, fasterize, knitr, haven, tidyverse, janitor, glue, sf, here, gt, kableExtra, fs, glue)

data_j2<-st_read(
  here("data/data_j2/data_j2.shp"), 
  quiet = TRUE)

provincias<-sf::st_read(
  here::here("data/QLAB_MIDAGRI_1.gdb"), 
  layer = "Provincias", 
  quiet=TRUE)

raster_import<- function(file){
  st_as_sf(st_as_sfc(st_bbox(read_stars(file, crs = 4326)))) %>% 
    mutate(name=sub(".*PLANET_IR *(.*?) *.tif*", "\\1", file)) %>% 
    rename(geometry=x)
}

myraster4<-
  fs::dir_ls("la_libertad/imagenes/IR/") %>% 
  map(raster_import) %>% 
  reduce(bind_rows) %>% 
  st_as_sf(sf_column_name = "geometry")

```

```{r}
#| eval: false

# loop
export_data_j2<- function(number){
  
  fs::dir_create(here("data", glue("data_j2_", number)))
  data_j2 %>% 
    filter(as.numeric(P403_MES) <= number) %>% 
    st_as_sf(sf_column_name = "geometry") %>% 
    st_write(here("data", glue("data_j2_", number), 
                  glue("data_j2_", number, ".shp")), 
             delete_layer = TRUE, quiet = TRUE) 

}

c(1:11) %>% 
  walk(export_data_j2)

```

```{r}

import_data_j2<- function(number){
  
  data_j2 %>% 
    filter(as.numeric(P403_MES) <= number)

}

data_j2_loop<- 
  c(1:11) %>% 
  map(import_data_j2)

```

Si visualizáramos los lotes de cultivo en comparación con los cuadrantes rásters veremos lo siguiente:

```{r}

multiplots<-function(num){
  
  myraster5 <- 
    myraster4 %>% 
    mutate(
      within=st_contains(
        geometry, 
        data_j2_loop[[num]]
        ) %>% 
        lengths > 0
    )
  
  # pp<-
    ggplot() + 
    geom_sf(data = provincias, size = 0.05, fill = "transparent") +
    geom_sf(data=myraster5, aes(fill=within), alpha = 0.5) + 
    geom_sf(data=data_j2_loop[[num]], 
            aes(geometry=geometry), 
            fill = "magenta", color = "magenta", size = 3) +
    geom_sf_text(data = myraster5, aes(label = name), size = 6) +
    scale_fill_manual(values = c("grey", "seagreen3"), labels = c("No", "Sí")) +
    theme_void() + 
    coord_sf(default_crs = sf::st_crs(4326), crs = sf::st_crs(4326)) +
    guides(fill=guide_legend(title="Descargar")) +
    theme(legend.key.size = unit(2, 'cm'), #change legend key size
          legend.key.height = unit(2, 'cm'), #change legend key height
          legend.key.width = unit(2, 'cm'), #change legend key width
          legend.title = element_text(size=18), #change legend title font size
          legend.text = element_text(size=16)) #change legend text font size
  
  # print(pp)
  # cat('\n\n')
}



```

```{r, echo = FALSE, results = 'asis'}
#| label: fig-rasterloop
#| fig-cap: Lotes según mes 2021
#| fig-subcap:
#| - Enero 01
#| - Febrero 02
#| - Marzo 03
#| - Abril 04
#| - Mayo 05
#| - Junio 06
#| - Julio 07
#| - Agosto 08
#| - Setiembre 09
#| - Octubre 10
#| - Noviembre 11
#| fig-width: 40
#| fig-height: 37.808
# era cuestion de aumentar las dimensiones fig un poco mas.
knitr::opts_chunk$set(fig.retina = 1)

c(1:11) %>%
  map(multiplots)-> all_plots

walk(all_plots, print)

```

